import { useEffect, useState } from 'react'
import { Link, NavLink, Outlet, useNavigate } from 'react-router-dom'
import { api } from '../lib/api'
import type { Health } from '../lib/types'
import { useAuth } from '../context/AuthContext'

const NAV = [
  { to: '/dashboard', label: 'Dashboard', icon: '📊' },
  { to: '/resume', label: 'Resume', icon: '📄' },
  { to: '/interview', label: 'Interview', icon: '🎙️' },
  { to: '/report', label: 'Reports', icon: '📈' },
  { to: '/roadmap', label: 'Roadmap', icon: '🗺️' },
]

export default function Layout() {
  const { user, logout } = useAuth()
  const navigate = useNavigate()
  const [health, setHealth] = useState<Health | null>(null)
  const [menuOpen, setMenuOpen] = useState(false)

  useEffect(() => { api.health().then(setHealth).catch(() => undefined) }, [])

  const links = user?.role === 'admin'
    ? [...NAV, { to: '/admin', label: 'Admin', icon: '🛡️' }]
    : NAV

  return (
    <div className="min-h-screen">
      <header className="sticky top-0 z-40 border-b border-ink-700/70 bg-ink-950/80 backdrop-blur">
        <div className="mx-auto flex h-16 max-w-7xl items-center gap-4 px-4 sm:px-6">
          <Link to="/dashboard" className="flex items-center gap-2 font-bold text-white">
            <span className="grid h-8 w-8 place-items-center rounded-lg bg-brand-500/20 text-base">🎯</span>
            <span className="hidden sm:inline">InterviewAce<span className="text-brand-400"> AI</span></span>
          </Link>

          <nav className="ml-2 hidden flex-1 items-center gap-1 md:flex">
            {links.map((link) => (
              <NavLink key={link.to} to={link.to}
                className={({ isActive }) =>
                  `rounded-lg px-3 py-2 text-sm font-medium transition ${
                    isActive ? 'bg-brand-500/15 text-brand-400' : 'text-slate-400 hover:text-slate-100'}`}>
                <span className="mr-1.5">{link.icon}</span>{link.label}
              </NavLink>
            ))}
          </nav>

          <div className="ml-auto flex items-center gap-3">
            {health && <EngineBadge health={health} />}
            <div className="hidden text-right sm:block">
              <div className="text-sm font-medium text-slate-200">
                {user?.full_name || user?.email}
              </div>
              <div className="text-xs text-slate-500">{user?.target_role}</div>
            </div>
            <button className="btn-ghost !px-3 !py-2"
                    onClick={() => { logout(); navigate('/login') }}>
              Sign out
            </button>
            <button className="btn-ghost !px-3 !py-2 md:hidden"
                    onClick={() => setMenuOpen((open) => !open)} aria-label="Menu">☰</button>
          </div>
        </div>

        {menuOpen && (
          <nav className="border-t border-ink-700/70 px-4 py-2 md:hidden">
            {links.map((link) => (
              <NavLink key={link.to} to={link.to} onClick={() => setMenuOpen(false)}
                className={({ isActive }) =>
                  `block rounded-lg px-3 py-2 text-sm ${
                    isActive ? 'bg-brand-500/15 text-brand-400' : 'text-slate-300'}`}>
                <span className="mr-2">{link.icon}</span>{link.label}
              </NavLink>
            ))}
          </nav>
        )}
      </header>

      <main className="mx-auto max-w-7xl px-4 py-8 sm:px-6">
        <Outlet />
      </main>

      <footer className="mx-auto max-w-7xl px-4 pb-10 text-xs text-slate-600 sm:px-6">
        InterviewAce AI v{health?.version ?? '1.0.0'} · Resume analysis, mock interviews and
        learning roadmaps · Built for the 22AIE301 project.
      </footer>
    </div>
  )
}

/**
 * Shows whether a real LLM is answering or the offline engine is.
 *
 * This is on screen at all times on purpose. A demo where everyone assumes the
 * model is live while it has quietly fallen back to templates is how you end
 * up defending numbers you cannot explain.
 */
function EngineBadge({ health }: { health: Health }) {
  const live = health.llm.available
  return (
    <span
      title={live
        ? `Questions and feedback are generated by ${health.llm.model}.`
        : 'No API key configured - running on the built-in question bank and heuristic scorer.'}
      className={`chip hidden lg:inline-flex ${
        live ? 'border-emerald-500/30 bg-emerald-500/10 text-emerald-300'
             : 'border-amber-500/30 bg-amber-500/10 text-amber-300'}`}>
      <span className={`h-1.5 w-1.5 rounded-full ${live ? 'bg-emerald-400' : 'bg-amber-400'}`} />
      {live ? health.llm.model : 'Offline engine'}
    </span>
  )
}
